# CI for command line NodeJS Applications
name: nodejs
on: [push, pull_request]

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        node: ['10']
        os: ['ubuntu-latest']

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install -g node-gyp && npm install  
        
      - name: Run tests
        run: npm run test && npm run report

      - name: Run tests
        run: npm run build
